let GOT_SKILLS = "GOT_SKILLS";
let ERROR_IN_REQUEST = "ERROR_IN_REQUEST";
let ADD_SKILL = "ADD_SKILL";
let REMOVE_SKILL = "REMOVE_SKILL";
let GOT_GIT_USER = "GOT_GIT_USER";

export {
	GOT_SKILLS,
	ERROR_IN_REQUEST,
  ADD_SKILL,
  REMOVE_SKILL,
  GOT_GIT_USER
}